name: Deploy to Azure App Service

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # Change this to your desired Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Replace this with your requirements file name

    - name: Deploy to Azure Web App
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az webapp up -n oaweb-$RANDOM --resource-group OA_Zone --plan oasp-$RANDOM --runtime PYTHON:3.9 --sku B2
        
        #az webapp deployment source config-local-git --name <your_webapp_name> --resource-group <your_resource_group_name> --query url --output tsv
        #git remote add azure <your_deployment_url>
        #git push azure HEAD:refs/heads/main --force # Change this to your desired branch name
